name: student_app
description: A comprehensive Flutter app for students to manage their academic activities.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  provider: ^6.0.5
  http: ^1.1.0
  file_picker: ^5.3.3
  path_provider: ^2.1.0
  shared_preferences: ^2.2.0
  flutter_spinkit: ^5.2.0
  intl: ^0.18.1
  flutter_markdown: ^0.6.17
  fl_chart: ^0.63.0
  cached_network_image: ^3.2.3
  shimmer: ^3.0.0
  url_launcher: ^6.1.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: SFPro
      fonts:
        - asset: assets/fonts/SF-Pro-Text-Regular.otf
          weight: 400
        - asset: assets/fonts/SF-Pro-Text-Medium.otf
          weight: 500
        - asset: assets/fonts/SF-Pro-Text-Bold.otf
          weight: 700